services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 456123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 30
    command: postgres -c listen_addresses='*'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  init:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: 456123
      DB_NAME: task_manager

volumes:
  postgres_data:
